#!/bin/bash
# Usage: test_render_params.sh <skill.md>
# Renders the params file with render_params.sh from test values and checks the result and the error cases.
# Prints "RENDER PASS" or exits 1.
set -u
source "$(cd "$(dirname "$0")" && pwd)/test_env.sh" "$@"
SKILL=${1:?usage: test_render_params.sh <skill.md>}
HERE=$(cd "$(dirname "$0")" && pwd)
gv() { awk -F'\t' -v k="$1" '$1 == k {print $2; exit}' "$HERE/fixtures/gate_values.tsv"; }
V="$TEST_TMP/values.tsv"; O="$TEST_TMP/out.yaml"; RL=$(gv TEST_READ_LENGTH); fail=0
values() { printf '%s\t%s\n' VERSION "$(gv PIPELINE_REVISION)" SAMPLESHEET_CSV test_samplesheet.csv CONTRASTS_CSV test_contrasts.csv \
  SOURCE fastq OUTDIR results/2026-10-01_test MULTIQC_TITLE 261001 FASTA_PATH /data/genome.fa GTF_PATH /data/genes.gtf \
  STAR_INDEX "" RUN_RMATS true RUN_DEXSEQ_EXON false RUN_EDGER_EXON false RUN_DEXSEQ_DTU true \
  RUN_SUPPA false READ_LENGTH "$RL" PAIRED_DESIGN false RMATS_NOVEL false MIN_SAMPS_GENE_EXPR 4 MIN_SAMPS_FEATURE 2 > "$V"; }
render() { rm -f "$O"; bash "$HERE/render_params.sh" "$SKILL" "$V" "$O" > "$TEST_TMP/log" 2>&1; }
values
if render; then
  grep -q '{' "$O" && { echo "FAIL: case full: placeholder left"; fail=1; }
  grep -q '^star_index:' "$O" && { echo "FAIL: case full: the empty star_index line was not deleted"; fail=1; }
  # the pipeline always builds its own Salmon index; gate HAS_MAX_PARAMS=no (an undeclared key stops the launch).
  grep -q '^salmon_index:' "$O" && { echo "FAIL: case full: salmon_index must never be written"; fail=1; }
  [ "$(gv HAS_MAX_PARAMS)" = no ] && grep -qE '^max_(cpus|memory|time):' "$O" && { echo "FAIL: case full: max_cpus/max_memory/max_time are not parameters of this revision"; fail=1; }
  for l in "# nf-core/rnasplice $(gv PIPELINE_REVISION) parameters — generated by /nfcore-rnasplice-setup" \
           'input: "test_samplesheet.csv"' 'contrasts: "test_contrasts.csv"' 'outdir: "results/2026-10-01_test"' \
           'fasta: "/data/genome.fa"' 'gtf: "/data/genes.gtf"' 'gencode: false' 'save_reference: false' \
           'aligner: "star"' 'pseudo_aligner: "salmon"' \
           'multiqc_title: "261001"' 'source: "fastq"' "rmats_read_len: $RL" \
           'rmats: true' 'dexseq_exon: false' 'edger_exon: false' 'dexseq_dtu: true' 'suppa: false' 'sashimi_plot: false' \
           'rmats_paired_stats: false' 'diffsplice_paired: false' 'min_samps_gene_expr: 4' 'min_samps_feature_expr: 2' 'min_samps_feature_prop: 2'; do
    grep -qxF -- "$l" "$O" || { echo "FAIL: case full: line missing: $l"; fail=1; }
  done
  [ -z "$(grep -oE '^[A-Za-z_0-9]+:' "$O" | sort | uniq -d)" ] || { echo "FAIL: case full: repeated key"; fail=1; }
else echo "FAIL: case full: render failed: $(cat "$TEST_TMP/log")"; fail=1; fi
values; sed -i 's#^STAR_INDEX\t$#STAR_INDEX\t/data/index/star#' "$V"
render && grep -qxF 'star_index: "/data/index/star"' "$O" || { echo "FAIL: case star_index_set"; fail=1; }
values; sed -i '/^STAR_INDEX\t/d' "$V"
render && ! grep -q '^star_index:' "$O" || { echo "FAIL: case star_index_absent"; fail=1; }
values; sed -i '/^RUN_SUPPA\t/d' "$V"
if render || [ -e "$O" ] || ! grep -qF 'no value for {RUN_SUPPA}' "$TEST_TMP/log"; then echo "FAIL: case missing_value"; fail=1; fi
values; sed -i 's#^OUTDIR\t.*#OUTDIR\t#' "$V"
if render || [ -e "$O" ] || ! grep -qF 'no value for {OUTDIR}' "$TEST_TMP/log"; then echo "FAIL: case empty_required_value"; fail=1; fi
values; sed -i 's#^OUTDIR\t.*#OUTDIR\t{X}#' "$V"
if render || [ -e "$O" ] || ! grep -qF 'contains a placeholder' "$TEST_TMP/log"; then echo "FAIL: case placeholder_in_value"; fail=1; fi
forbidden_ran && fail=1
[ $fail -eq 0 ] && echo "RENDER PASS" || exit 1
